/* =========================================================================
   LISTES DE VOCABULAIRE  —  c'est le seul fichier à modifier pour changer les mots.
   =========================================================================

   Comment ça marche :
   - Chaque liste a un "name" (le texte du bouton), un "icon" (un emoji) et
     un tableau "words".
   - Chaque mot a "en" (anglais) et "fr" (français).

   PLUSIEURS TRADUCTIONS POSSIBLES :
   - "en" comme "fr" peuvent être une chaîne :           { en: "dog", fr: "chien" }
     ...ou un tableau de traductions acceptées :         { en: "teacher",
                                                            fr: ["professeur", "maître", "maîtresse"] }
   - La 1re valeur du tableau est celle qui s'affiche (le mot montré, et le
     bouton "bonne réponse"). Les suivantes sont juste "aussi acceptées" :
     elles ne seront jamais proposées comme mauvaise réponse, et si l'enfant
     en choisit une, c'est compté juste.

   Après avoir modifié ce fichier : recharge la page (ou redéploie).

   NIVEAU :
   - "level: 'avance'" classe une liste (ou un mot) en vocabulaire avancé.
     Sans "level", c'est "primaire".
   - Le "level" peut se mettre sur une LISTE  { name: ..., level: 'avance', words: [...] }
     ET/OU sur un MOT précis  { en: 'hedgehog', fr: 'hérisson', level: 'avance' }.
     Un mot sans "level" hérite de celui de sa liste : une même liste peut donc
     mélanger des mots primaire et des mots avancés.
   - Sur l'écran d'accueil, le sélecteur "Niveau" (Primaire / Avancé / Tout)
     filtre les MOTS affichés (et masque les listes qui n'ont plus aucun mot).

   Les 25 premières listes sont thématiques : surtout du primaire (cycles 2 et 3),
   plus quelques mots "level: 'avance'" en fin de liste. Les 15 dernières listes
   ("level: 'avance'" en entier) portent sur du vocabulaire avancé (niveau A2–B1).
   Au premier lancement, seule la 1re liste est cochée.

   Conseils :
   - "icon" est facultatif (📚 par défaut). Un seul emoji.
   - Au moins 6 mots par liste (idéalement 8+) pour que le niveau "Difficile"
     (6 propositions) ait assez de choix.
   - Évite, dans une même liste, deux mots dont la traduction PRINCIPALE est identique.
   - Les accents et les majuscules ne comptent pas pour la correction.
   - Attention aux virgules : une après chaque { en: ..., fr: ... }.
   ========================================================================= */

window.VOCAB_LISTS = [
  {
    name: "Se saluer et être poli",
    icon: "👋",
    words: [
      { en: "hello", fr: ["bonjour", "salut"] },
      { en: "goodbye", fr: "au revoir" },
      { en: "good night", fr: "bonne nuit" },
      { en: "please", fr: ["s'il te plaît", "s'il vous plaît"] },
      { en: ["thank you", "thanks"], fr: "merci" },
      { en: "you're welcome", fr: ["de rien", "je t'en prie"] },
      { en: "yes", fr: "oui" },
      { en: "no", fr: "non" },
      { en: "sorry", fr: ["désolé", "pardon"] },
      { en: "excuse me", fr: ["excusez-moi", "pardon"] },
      { en: "see you soon", fr: "à bientôt" },
      { en: "welcome", fr: "bienvenue" },
      { en: "to greet", fr: "saluer", level: "avance" },
      { en: "to introduce", fr: "présenter", level: "avance" },
      { en: "polite", fr: "poli", level: "avance" },
      { en: "manners", fr: "les bonnes manières", level: "avance" },
      { en: "handshake", fr: "poignée de main", level: "avance" },
    ],
  },
  {
    name: "Les nombres (1 à 20)",
    icon: "🔢",
    words: [
      { en: "one", fr: "un" },
      { en: "two", fr: "deux" },
      { en: "three", fr: "trois" },
      { en: "four", fr: "quatre" },
      { en: "five", fr: "cinq" },
      { en: "six", fr: "six" },
      { en: "seven", fr: "sept" },
      { en: "eight", fr: "huit" },
      { en: "nine", fr: "neuf" },
      { en: "ten", fr: "dix" },
      { en: "eleven", fr: "onze" },
      { en: "twelve", fr: "douze" },
      { en: "thirteen", fr: "treize" },
      { en: "fourteen", fr: "quatorze" },
      { en: "fifteen", fr: "quinze" },
      { en: "sixteen", fr: "seize" },
      { en: "seventeen", fr: "dix-sept" },
      { en: "eighteen", fr: "dix-huit" },
      { en: "nineteen", fr: "dix-neuf" },
      { en: "twenty", fr: "vingt" },
      { en: "thirty", fr: "trente", level: "avance" },
      { en: "hundred", fr: "cent", level: "avance" },
      { en: "thousand", fr: "mille", level: "avance" },
      { en: "first", fr: "premier", level: "avance" },
      { en: "second", fr: "deuxième", level: "avance" },
      { en: "third", fr: "troisième", level: "avance" },
      { en: "a half", fr: "une moitié", level: "avance" },
      { en: "to count", fr: "compter", level: "avance" },
    ],
  },
  {
    name: "Les couleurs",
    icon: "🎨",
    words: [
      { en: "red", fr: "rouge" },
      { en: "blue", fr: "bleu" },
      { en: "green", fr: "vert" },
      { en: "yellow", fr: "jaune" },
      { en: "orange", fr: "orange" },
      { en: "pink", fr: "rose" },
      { en: "purple", fr: ["violet", "mauve"] },
      { en: "brown", fr: ["marron", "brun"] },
      { en: "black", fr: "noir" },
      { en: "white", fr: "blanc" },
      { en: ["grey", "gray"], fr: "gris" },
      { en: "gold", fr: ["doré", "or"] },
      { en: "silver", fr: "argenté", level: "avance" },
      { en: "dark", fr: "foncé", level: "avance" },
      { en: "bright", fr: "vif", level: "avance" },
      { en: "pale", fr: "pâle", level: "avance" },
      { en: "colourful", fr: "coloré", level: "avance" },
      { en: "plain", fr: "uni", level: "avance" },
    ],
  },
  {
    name: "Les jours de la semaine",
    icon: "📅",
    words: [
      { en: "Monday", fr: "lundi" },
      { en: "Tuesday", fr: "mardi" },
      { en: "Wednesday", fr: "mercredi" },
      { en: "Thursday", fr: "jeudi" },
      { en: "Friday", fr: "vendredi" },
      { en: "Saturday", fr: "samedi" },
      { en: "Sunday", fr: "dimanche" },
      { en: "today", fr: "aujourd'hui" },
      { en: "tomorrow", fr: "demain" },
      { en: "yesterday", fr: "hier" },
      { en: "week", fr: "semaine" },
      { en: "weekend", fr: "week-end", level: "avance" },
      { en: "weekday", fr: "jour de semaine", level: "avance" },
      { en: "the day before yesterday", fr: "avant-hier", level: "avance" },
      { en: "the day after tomorrow", fr: "après-demain", level: "avance" },
      { en: "daily", fr: "quotidien", level: "avance" },
    ],
  },
  {
    name: "Les mois de l'année",
    icon: "🗓️",
    words: [
      { en: "January", fr: "janvier" },
      { en: "February", fr: "février" },
      { en: "March", fr: "mars" },
      { en: "April", fr: "avril" },
      { en: "May", fr: "mai" },
      { en: "June", fr: "juin" },
      { en: "July", fr: "juillet" },
      { en: "August", fr: "août" },
      { en: "September", fr: "septembre" },
      { en: "October", fr: "octobre" },
      { en: "November", fr: "novembre" },
      { en: "December", fr: "décembre" },
      { en: "month", fr: "mois", level: "avance" },
      { en: "year", fr: "année", level: "avance" },
      { en: "season", fr: "saison", level: "avance" },
      { en: "century", fr: "siècle", level: "avance" },
      { en: "calendar", fr: "calendrier", level: "avance" },
      { en: "leap year", fr: "année bissextile", level: "avance" },
    ],
  },
  {
    name: "La famille",
    icon: "👪",
    words: [
      { en: ["mother", "mum", "mummy"], fr: ["mère", "maman"] },
      { en: ["father", "dad", "daddy"], fr: ["père", "papa"] },
      { en: "sister", fr: "sœur" },
      { en: "brother", fr: "frère" },
      { en: ["grandmother", "granny", "grandma"], fr: ["grand-mère", "mamie"] },
      { en: ["grandfather", "grandpa", "grandad"], fr: ["grand-père", "papi"] },
      { en: "parents", fr: "parents" },
      { en: "baby", fr: "bébé" },
      { en: "aunt", fr: "tante" },
      { en: "uncle", fr: "oncle" },
      { en: "cousin", fr: "cousin" },
      { en: "son", fr: "fils" },
      { en: "daughter", fr: "fille" },
      { en: "niece", fr: "nièce", level: "avance" },
      { en: "nephew", fr: "neveu", level: "avance" },
      { en: "twin", fr: "jumeau", level: "avance" },
      { en: "stepmother", fr: "belle-mère", level: "avance" },
      { en: "godmother", fr: "marraine", level: "avance" },
      { en: "relative", fr: "membre de la famille", level: "avance" },
    ],
  },
  {
    name: "Le corps et le visage",
    icon: "🧑",
    words: [
      { en: "head", fr: "tête" },
      { en: "hair", fr: "cheveux" },
      { en: "face", fr: "visage" },
      { en: "eye", fr: "œil" },
      { en: "ear", fr: "oreille" },
      { en: "nose", fr: "nez" },
      { en: "mouth", fr: "bouche" },
      { en: "tooth", fr: "dent" },
      { en: ["stomach", "tummy"], fr: ["ventre", "estomac"] },
      { en: "arm", fr: "bras" },
      { en: "hand", fr: "main" },
      { en: "finger", fr: "doigt" },
      { en: "leg", fr: "jambe" },
      { en: "foot", fr: "pied" },
      { en: "knee", fr: "genou" },
      { en: "neck", fr: "cou", level: "avance" },
      { en: "back", fr: "dos", level: "avance" },
      { en: "chest", fr: "poitrine", level: "avance" },
      { en: "toe", fr: "orteil", level: "avance" },
      { en: "tongue", fr: "langue", level: "avance" },
      { en: "nail", fr: "ongle", level: "avance" },
    ],
  },
  {
    name: "Animaux familiers et de la ferme",
    icon: "🐮",
    words: [
      { en: "dog", fr: "chien" },
      { en: "cat", fr: "chat" },
      { en: "rabbit", fr: "lapin" },
      { en: "hamster", fr: "hamster" },
      { en: "goldfish", fr: "poisson rouge" },
      { en: "horse", fr: "cheval" },
      { en: "cow", fr: "vache" },
      { en: "pig", fr: "cochon" },
      { en: "sheep", fr: "mouton" },
      { en: "hen", fr: "poule" },
      { en: "duck", fr: "canard" },
      { en: "goat", fr: "chèvre" },
      { en: "donkey", fr: "âne" },
      { en: "rooster", fr: "coq", level: "avance" },
      { en: "lamb", fr: "agneau", level: "avance" },
      { en: "kitten", fr: "chaton", level: "avance" },
      { en: "puppy", fr: "chiot", level: "avance" },
      { en: "to bark", fr: "aboyer", level: "avance" },
      { en: "tail", fr: "queue", level: "avance" },
    ],
  },
  {
    name: "Les animaux sauvages",
    icon: "🦁",
    words: [
      { en: "lion", fr: "lion" },
      { en: "tiger", fr: "tigre" },
      { en: "elephant", fr: "éléphant" },
      { en: "monkey", fr: "singe" },
      { en: "bear", fr: "ours" },
      { en: "wolf", fr: "loup" },
      { en: "fox", fr: "renard" },
      { en: "snake", fr: "serpent" },
      { en: "crocodile", fr: "crocodile" },
      { en: "giraffe", fr: "girafe" },
      { en: "zebra", fr: "zèbre" },
      { en: "kangaroo", fr: "kangourou" },
      { en: "panda", fr: "panda" },
      { en: "whale", fr: "baleine" },
      { en: "hedgehog", fr: "hérisson", level: "avance" },
      { en: "squirrel", fr: "écureuil", level: "avance" },
      { en: "owl", fr: "hibou", level: "avance" },
      { en: "dolphin", fr: "dauphin", level: "avance" },
      { en: "shark", fr: "requin", level: "avance" },
      { en: "eagle", fr: "aigle", level: "avance" },
    ],
  },
  {
    name: "La nourriture",
    icon: "🍽️",
    words: [
      { en: "bread", fr: "pain" },
      { en: "butter", fr: "beurre" },
      { en: "cheese", fr: "fromage" },
      { en: "egg", fr: "œuf" },
      { en: "milk", fr: "lait" },
      { en: "water", fr: "eau" },
      { en: ["juice", "fruit juice"], fr: ["jus", "jus de fruits"] },
      { en: "meat", fr: "viande" },
      { en: "chicken", fr: "poulet" },
      { en: "fish", fr: "poisson" },
      { en: "rice", fr: "riz" },
      { en: "pasta", fr: "pâtes" },
      { en: "soup", fr: "soupe" },
      { en: ["cake", "sponge cake"], fr: "gâteau" },
      { en: "breakfast", fr: "petit-déjeuner", level: "avance" },
      { en: "lunch", fr: "déjeuner", level: "avance" },
      { en: "dinner", fr: "dîner", level: "avance" },
      { en: "flour", fr: "farine", level: "avance" },
      { en: "sugar", fr: "sucre", level: "avance" },
      { en: "honey", fr: "miel", level: "avance" },
    ],
  },
  {
    name: "Les fruits et les légumes",
    icon: "🍎",
    words: [
      { en: "apple", fr: "pomme" },
      { en: "banana", fr: "banane" },
      { en: "orange", fr: "orange" },
      { en: "strawberry", fr: "fraise" },
      { en: "cherry", fr: "cerise" },
      { en: "grape", fr: "raisin" },
      { en: "lemon", fr: "citron" },
      { en: "pear", fr: "poire" },
      { en: "pineapple", fr: "ananas" },
      { en: "tomato", fr: "tomate" },
      { en: "potato", fr: "pomme de terre" },
      { en: "carrot", fr: "carotte" },
      { en: "onion", fr: "oignon" },
      { en: ["salad", "lettuce"], fr: ["salade", "laitue"] },
      { en: "peach", fr: "pêche", level: "avance" },
      { en: "plum", fr: "prune", level: "avance" },
      { en: "raspberry", fr: "framboise", level: "avance" },
      { en: "cucumber", fr: "concombre", level: "avance" },
      { en: "mushroom", fr: "champignon", level: "avance" },
      { en: "garlic", fr: "ail", level: "avance" },
    ],
  },
  {
    name: "Les vêtements",
    icon: "👕",
    words: [
      { en: "shirt", fr: "chemise" },
      { en: "T-shirt", fr: "tee-shirt" },
      { en: ["jumper", "sweater", "pullover"], fr: ["pull", "pull-over"] },
      { en: ["trousers", "pants"], fr: "pantalon" },
      { en: "dress", fr: "robe" },
      { en: "skirt", fr: "jupe" },
      { en: "coat", fr: "manteau" },
      { en: "jacket", fr: ["veste", "blouson"] },
      { en: ["shoes", "trainers"], fr: ["chaussures", "baskets"] },
      { en: "socks", fr: "chaussettes" },
      { en: "hat", fr: "chapeau" },
      { en: "gloves", fr: "gants" },
      { en: "scarf", fr: "écharpe" },
      { en: "boots", fr: "bottes", level: "avance" },
      { en: "shorts", fr: "short", level: "avance" },
      { en: "pyjamas", fr: "pyjama", level: "avance" },
      { en: "belt", fr: "ceinture", level: "avance" },
      { en: "pocket", fr: "poche", level: "avance" },
      { en: "sleeve", fr: "manche", level: "avance" },
    ],
  },
  {
    name: "L'école et la classe",
    icon: "🎒",
    words: [
      { en: "school", fr: "école" },
      { en: "teacher", fr: ["professeur", "maître", "maîtresse", "instituteur"] },
      { en: ["pupil", "student"], fr: "élève" },
      { en: "book", fr: "livre" },
      { en: "pen", fr: "stylo" },
      { en: "pencil", fr: "crayon" },
      { en: ["eraser", "rubber"], fr: "gomme" },
      { en: "ruler", fr: "règle" },
      { en: "notebook", fr: "cahier" },
      { en: ["schoolbag", "school bag"], fr: ["cartable", "sac d'école"] },
      { en: "glue", fr: "colle" },
      { en: "scissors", fr: "ciseaux" },
      { en: "desk", fr: "bureau" },
      { en: ["board", "blackboard", "whiteboard"], fr: "tableau" },
      { en: "sharpener", fr: "taille-crayon", level: "avance" },
      { en: "folder", fr: "classeur", level: "avance" },
      { en: "textbook", fr: "manuel", level: "avance" },
      { en: "to spell", fr: "épeler", level: "avance" },
      { en: "handwriting", fr: "écriture", level: "avance" },
    ],
  },
  {
    name: "La maison",
    icon: "🏠",
    words: [
      { en: ["house", "home"], fr: "maison" },
      { en: "bedroom", fr: "chambre" },
      { en: "kitchen", fr: "cuisine" },
      { en: "bathroom", fr: "salle de bains" },
      { en: ["living room", "lounge"], fr: ["salon", "salle de séjour", "séjour"] },
      { en: "garden", fr: "jardin" },
      { en: "door", fr: "porte" },
      { en: "window", fr: "fenêtre" },
      { en: "wall", fr: "mur" },
      { en: "roof", fr: "toit" },
      { en: "bed", fr: "lit" },
      { en: "table", fr: "table" },
      { en: "chair", fr: "chaise" },
      { en: ["sofa", "couch", "settee"], fr: ["canapé", "sofa"] },
      { en: "floor", fr: "sol", level: "avance" },
      { en: "garage", fr: "garage", level: "avance" },
      { en: "key", fr: "clé", level: "avance" },
      { en: "mirror", fr: "miroir", level: "avance" },
      { en: "oven", fr: "four", level: "avance" },
      { en: "fridge", fr: "frigo", level: "avance" },
    ],
  },
  {
    name: "Le temps qu'il fait et les saisons",
    icon: "⛅",
    words: [
      { en: "spring", fr: "printemps" },
      { en: "summer", fr: "été" },
      { en: ["autumn", "fall"], fr: "automne" },
      { en: "winter", fr: "hiver" },
      { en: "sun", fr: "soleil" },
      { en: "rain", fr: "pluie" },
      { en: "wind", fr: "vent" },
      { en: "snow", fr: "neige" },
      { en: "cloud", fr: "nuage" },
      { en: ["storm", "thunderstorm"], fr: ["orage", "tempête"] },
      { en: "rainbow", fr: "arc-en-ciel" },
      { en: "ice", fr: "glace" },
      { en: ["hot", "warm"], fr: "chaud" },
      { en: "cold", fr: "froid" },
      { en: "weather", fr: "le temps qu'il fait", level: "avance" },
      { en: "temperature", fr: "température", level: "avance" },
      { en: "sunny", fr: "ensoleillé", level: "avance" },
      { en: "rainy", fr: "pluvieux", level: "avance" },
      { en: "windy", fr: "venteux", level: "avance" },
      { en: "wet", fr: "mouillé", level: "avance" },
    ],
  },
  {
    name: "Les émotions et les sensations",
    icon: "😀",
    words: [
      { en: "happy", fr: ["content", "heureux"] },
      { en: "sad", fr: "triste" },
      { en: "angry", fr: ["fâché", "en colère", "furieux"] },
      { en: ["scared", "afraid", "frightened"], fr: ["effrayé", "apeuré"] },
      { en: "tired", fr: "fatigué" },
      { en: "surprised", fr: "surpris" },
      { en: "excited", fr: "excité" },
      { en: "bored", fr: "ennuyé" },
      { en: ["ill", "sick"], fr: "malade" },
      { en: "hungry", fr: "affamé" },
      { en: "thirsty", fr: "assoiffé" },
      { en: "worried", fr: "inquiet" },
      { en: "calm", fr: "calme" },
      { en: "upset", fr: "contrarié", level: "avance" },
      { en: "lonely", fr: "seul", level: "avance" },
      { en: "embarrassed", fr: "gêné", level: "avance" },
      { en: "disappointed", fr: "déçu", level: "avance" },
      { en: "annoyed", fr: "agacé", level: "avance" },
      { en: "relaxed", fr: "détendu", level: "avance" },
    ],
  },
  {
    name: "Les verbes d'action",
    icon: "🏃",
    words: [
      { en: "to run", fr: "courir" },
      { en: "to jump", fr: ["sauter", "bondir"] },
      { en: "to walk", fr: "marcher" },
      { en: "to swim", fr: "nager" },
      { en: "to sing", fr: "chanter" },
      { en: "to dance", fr: "danser" },
      { en: "to read", fr: "lire" },
      { en: "to write", fr: "écrire" },
      { en: "to draw", fr: "dessiner" },
      { en: "to play", fr: "jouer" },
      { en: "to eat", fr: "manger" },
      { en: "to drink", fr: "boire" },
      { en: "to sleep", fr: "dormir" },
      { en: "to climb", fr: "grimper" },
      { en: "to crawl", fr: "ramper", level: "avance" },
      { en: "to kneel", fr: "s'agenouiller", level: "avance" },
      { en: "to stretch", fr: "s'étirer", level: "avance" },
      { en: "to chase", fr: "poursuivre", level: "avance" },
      { en: "to throw", fr: "lancer", level: "avance" },
      { en: "to kick", fr: "donner un coup de pied", level: "avance" },
    ],
  },
  {
    name: "Les verbes essentiels",
    icon: "🔑",
    words: [
      { en: "to be", fr: "être" },
      { en: "to have", fr: "avoir" },
      { en: "to go", fr: "aller" },
      { en: "to come", fr: "venir" },
      { en: "to see", fr: "voir" },
      { en: "to want", fr: ["vouloir", "désirer"] },
      { en: ["to like", "to enjoy"], fr: ["aimer", "aimer bien"] },
      { en: "to know", fr: ["savoir", "connaître"] },
      { en: "to give", fr: "donner" },
      { en: "to take", fr: "prendre" },
      { en: ["to say", "to tell"], fr: "dire" },
      { en: "to think", fr: ["penser", "réfléchir", "croire"] },
      { en: "to open", fr: "ouvrir" },
      { en: "to close", fr: ["fermer", "refermer"] },
      { en: "to become", fr: "devenir", level: "avance" },
      { en: "to bring", fr: "apporter", level: "avance" },
      { en: "to leave", fr: "partir", level: "avance" },
      { en: "to find", fr: "trouver", level: "avance" },
      { en: "to understand", fr: "comprendre", level: "avance" },
      { en: "to hold", fr: "tenir", level: "avance" },
    ],
  },
  {
    name: "Les métiers",
    icon: "👷",
    words: [
      { en: "teacher", fr: ["professeur", "maître", "maîtresse", "instituteur"] },
      { en: "doctor", fr: ["médecin", "docteur"] },
      { en: "nurse", fr: ["infirmier", "infirmière"] },
      { en: "farmer", fr: ["fermier", "agriculteur"] },
      { en: "baker", fr: "boulanger" },
      { en: ["firefighter", "fireman"], fr: "pompier" },
      { en: ["police officer", "policeman"], fr: ["policier", "gendarme"] },
      { en: ["cook", "chef"], fr: ["cuisinier", "cuisinière", "chef"] },
      { en: "dentist", fr: "dentiste" },
      { en: "vet", fr: "vétérinaire" },
      { en: "pilot", fr: "pilote" },
      { en: "singer", fr: ["chanteur", "chanteuse"] },
      { en: "painter", fr: "peintre" },
      { en: "engineer", fr: "ingénieur", level: "avance" },
      { en: "lawyer", fr: "avocat", level: "avance" },
      { en: "journalist", fr: "journaliste", level: "avance" },
      { en: "plumber", fr: "plombier", level: "avance" },
      { en: "mechanic", fr: "mécanicien", level: "avance" },
      { en: "hairdresser", fr: "coiffeur", level: "avance" },
    ],
  },
  {
    name: "La ville et les lieux",
    icon: "🏙️",
    words: [
      { en: "school", fr: "école" },
      { en: ["shop", "store"], fr: ["magasin", "boutique"] },
      { en: "park", fr: "parc" },
      { en: "library", fr: "bibliothèque" },
      { en: "hospital", fr: "hôpital" },
      { en: "museum", fr: "musée" },
      { en: ["cinema", "movie theater"], fr: "cinéma" },
      { en: ["station", "train station"], fr: "gare" },
      { en: "market", fr: "marché" },
      { en: "bakery", fr: "boulangerie" },
      { en: "restaurant", fr: "restaurant" },
      { en: "swimming pool", fr: "piscine" },
      { en: "playground", fr: ["cour de récréation", "cour"] },
      { en: "church", fr: "église", level: "avance" },
      { en: "castle", fr: "château", level: "avance" },
      { en: "factory", fr: "usine", level: "avance" },
      { en: "airport", fr: "aéroport", level: "avance" },
      { en: "bank", fr: "banque", level: "avance" },
      { en: "stadium", fr: "stade", level: "avance" },
    ],
  },
  {
    name: "Les transports",
    icon: "🚗",
    words: [
      { en: ["car", "automobile"], fr: ["voiture", "auto"] },
      { en: "bus", fr: ["bus", "autobus"] },
      { en: "train", fr: "train" },
      { en: ["plane", "aeroplane", "airplane"], fr: "avion" },
      { en: ["bike", "bicycle"], fr: ["vélo", "bicyclette"] },
      { en: "boat", fr: "bateau" },
      { en: "ship", fr: "navire" },
      { en: ["lorry", "truck"], fr: "camion" },
      { en: "taxi", fr: "taxi" },
      { en: "helicopter", fr: "hélicoptère" },
      { en: "tram", fr: "tramway" },
      { en: ["underground", "tube", "subway"], fr: "métro" },
      { en: "scooter", fr: "trottinette" },
      { en: "van", fr: "camionnette", level: "avance" },
      { en: "coach", fr: "autocar", level: "avance" },
      { en: "ferry", fr: "ferry", level: "avance" },
      { en: "ambulance", fr: "ambulance", level: "avance" },
      { en: "ticket", fr: "billet", level: "avance" },
      { en: "platform", fr: "quai", level: "avance" },
    ],
  },
  {
    name: "La nature",
    icon: "🌳",
    words: [
      { en: "tree", fr: "arbre" },
      { en: "flower", fr: "fleur" },
      { en: "grass", fr: ["herbe", "gazon"] },
      { en: "leaf", fr: "feuille" },
      { en: ["forest", "wood", "woods"], fr: ["forêt", "bois"] },
      { en: "mountain", fr: "montagne" },
      { en: "river", fr: "rivière" },
      { en: "lake", fr: "lac" },
      { en: ["sea", "ocean"], fr: ["mer", "océan"] },
      { en: "beach", fr: "plage" },
      { en: "field", fr: "champ" },
      { en: "hill", fr: "colline" },
      { en: "moon", fr: "lune" },
      { en: "star", fr: "étoile" },
      { en: "branch", fr: "branche", level: "avance" },
      { en: "root", fr: "racine", level: "avance" },
      { en: "seed", fr: "graine", level: "avance" },
      { en: "sand", fr: "sable", level: "avance" },
      { en: "wave", fr: "vague", level: "avance" },
      { en: "sunset", fr: "coucher du soleil", level: "avance" },
    ],
  },
  {
    name: "Halloween",
    icon: "🎃",
    words: [
      { en: "witch", fr: "sorcière" },
      { en: "ghost", fr: "fantôme" },
      { en: "pumpkin", fr: "citrouille" },
      { en: "skeleton", fr: "squelette" },
      { en: "bat", fr: "chauve-souris" },
      { en: "spider", fr: "araignée" },
      { en: "monster", fr: "monstre" },
      { en: "vampire", fr: "vampire" },
      { en: "broom", fr: ["balai", "balai de sorcière"] },
      { en: ["sweets", "candy"], fr: "bonbons" },
      { en: ["costume", "fancy dress"], fr: ["déguisement", "costume"] },
      { en: ["scary", "spooky"], fr: "effrayant" },
      { en: "werewolf", fr: "loup-garou", level: "avance" },
      { en: "zombie", fr: "zombie", level: "avance" },
      { en: "graveyard", fr: "cimetière", level: "avance" },
      { en: "cobweb", fr: "toile d'araignée", level: "avance" },
      { en: "haunted", fr: "hanté", level: "avance" },
    ],
  },
  {
    name: "Noël",
    icon: "🎄",
    words: [
      { en: "Christmas", fr: "Noël" },
      { en: ["Father Christmas", "Santa", "Santa Claus"], fr: "Père Noël" },
      { en: ["present", "gift"], fr: "cadeau" },
      { en: "Christmas tree", fr: ["sapin", "sapin de Noël"] },
      { en: "star", fr: "étoile" },
      { en: "snow", fr: "neige" },
      { en: "reindeer", fr: "renne" },
      { en: ["sleigh", "sledge"], fr: "traîneau" },
      { en: "bell", fr: "cloche" },
      { en: "candle", fr: "bougie" },
      { en: "snowman", fr: "bonhomme de neige" },
      { en: "holly", fr: "houx" },
      { en: "angel", fr: "ange" },
      { en: "wreath", fr: "couronne", level: "avance" },
      { en: "mistletoe", fr: "gui", level: "avance" },
      { en: "stocking", fr: "chaussette de Noël", level: "avance" },
      { en: "elf", fr: "lutin", level: "avance" },
      { en: "carol", fr: "chant de Noël", level: "avance" },
      { en: "nativity scene", fr: "crèche", level: "avance" },
    ],
  },
  {
    name: "Les adjectifs pour décrire",
    icon: "🔍",
    words: [
      { en: ["big", "large"], fr: ["grand", "gros"] },
      { en: ["small", "little"], fr: "petit" },
      { en: "long", fr: "long" },
      { en: "short", fr: "court" },
      { en: "new", fr: ["neuf", "nouveau"] },
      { en: "old", fr: ["vieux", "ancien"] },
      { en: ["fast", "quick"], fr: "rapide" },
      { en: "slow", fr: "lent" },
      { en: "easy", fr: "facile" },
      { en: ["hard", "difficult"], fr: ["difficile", "dur"] },
      { en: "strong", fr: "fort" },
      { en: "clean", fr: "propre" },
      { en: "dirty", fr: "sale" },
      { en: ["beautiful", "pretty"], fr: ["beau", "joli"] },
      { en: "heavy", fr: "lourd", level: "avance" },
      { en: "light", fr: "léger", level: "avance" },
      { en: "soft", fr: "doux", level: "avance" },
      { en: "loud", fr: "bruyant", level: "avance" },
      { en: "empty", fr: "vide", level: "avance" },
      { en: "high", fr: "haut", level: "avance" },
    ],
  },

  /* ============================= VOCABULAIRE AVANCÉ ============================= */

  {
    name: "Le caractère",
    icon: "😎",
    level: "avance",
    words: [
      { en: "confident", fr: "sûr de soi" },
      { en: "shy", fr: "timide" },
      { en: "nervous", fr: "nerveux" },
      { en: "jealous", fr: "jaloux" },
      { en: "generous", fr: "généreux" },
      { en: "selfish", fr: "égoïste" },
      { en: "curious", fr: "curieux" },
      { en: "stubborn", fr: "têtu" },
      { en: "brave", fr: "courageux" },
      { en: "honest", fr: "honnête" },
      { en: "lazy", fr: "paresseux" },
      { en: "cheerful", fr: "joyeux" },
      { en: "rude", fr: "impoli" },
      { en: "friendly", fr: ["amical", "sympathique"] },
      { en: "proud", fr: "fier" },
    ],
  },
  {
    name: "Décrire une personne",
    icon: "🧑‍🦱",
    level: "avance",
    words: [
      { en: "freckles", fr: "taches de rousseur" },
      { en: "wrinkles", fr: "rides" },
      { en: "curly hair", fr: "cheveux bouclés" },
      { en: "straight hair", fr: "cheveux raides" },
      { en: "bald", fr: "chauve" },
      { en: "beard", fr: "barbe" },
      { en: "moustache", fr: "moustache" },
      { en: "slim", fr: ["mince", "svelte"] },
      { en: "plump", fr: "potelé" },
      { en: "elderly", fr: ["âgé", "d'un certain âge"] },
      { en: "good-looking", fr: ["beau", "séduisant"] },
      { en: "ponytail", fr: "queue de cheval" },
      { en: "dimples", fr: "fossettes" },
      { en: "tanned", fr: "bronzé" },
    ],
  },
  {
    name: "La maison, en détail",
    icon: "🛋️",
    level: "avance",
    words: [
      { en: "attic", fr: "grenier" },
      { en: "basement", fr: ["sous-sol", "cave"] },
      { en: "hallway", fr: ["couloir", "entrée"] },
      { en: "ceiling", fr: "plafond" },
      { en: "staircase", fr: "escalier" },
      { en: "wardrobe", fr: "armoire" },
      { en: "cupboard", fr: "placard" },
      { en: "drawer", fr: "tiroir" },
      { en: "shelf", fr: "étagère" },
      { en: "cushion", fr: "coussin" },
      { en: "blanket", fr: "couverture" },
      { en: "curtains", fr: "rideaux" },
      { en: "sink", fr: "évier" },
      { en: "tap", fr: "robinet" },
      { en: "fireplace", fr: "cheminée" },
    ],
  },
  {
    name: "En ville et se déplacer",
    icon: "🚦",
    level: "avance",
    words: [
      { en: "pavement", fr: "trottoir" },
      { en: "crossroads", fr: "carrefour" },
      { en: "roundabout", fr: "rond-point" },
      { en: "traffic lights", fr: "feux (de circulation)" },
      { en: "pedestrian", fr: "piéton" },
      { en: "motorway", fr: "autoroute" },
      { en: "lane", fr: "voie" },
      { en: "signpost", fr: "panneau" },
      { en: "town hall", fr: "mairie" },
      { en: "suburb", fr: "banlieue" },
      { en: "corner", fr: "coin" },
      { en: "bridge", fr: "pont" },
      { en: "crowd", fr: "foule" },
      { en: "traffic jam", fr: "embouteillage" },
    ],
  },
  {
    name: "Nature et environnement",
    icon: "🌍",
    level: "avance",
    words: [
      { en: "stream", fr: "ruisseau" },
      { en: "pond", fr: "mare" },
      { en: "cliff", fr: "falaise" },
      { en: "cave", fr: "grotte" },
      { en: "valley", fr: "vallée" },
      { en: "meadow", fr: "prairie" },
      { en: "shore", fr: "rivage" },
      { en: "tide", fr: "marée" },
      { en: "drought", fr: "sécheresse" },
      { en: "flood", fr: "inondation" },
      { en: "pollution", fr: "pollution" },
      { en: "litter", fr: ["déchets", "ordures"] },
      { en: "wildlife", fr: "faune sauvage" },
      { en: "endangered", fr: "en voie de disparition" },
      { en: "to recycle", fr: "recycler" },
    ],
  },
  {
    name: "La météo, en détail",
    icon: "🌦️",
    level: "avance",
    words: [
      { en: "drizzle", fr: "bruine" },
      { en: "shower", fr: "averse" },
      { en: "thunder", fr: "tonnerre" },
      { en: "lightning", fr: "éclair" },
      { en: "breeze", fr: "brise" },
      { en: "gale", fr: "bourrasque" },
      { en: "frost", fr: "gel" },
      { en: "hail", fr: "grêle" },
      { en: "mist", fr: "brume" },
      { en: "humid", fr: "humide" },
      { en: "overcast", fr: "couvert" },
      { en: "forecast", fr: "prévisions (météo)" },
      { en: "freezing", fr: "glacial" },
      { en: "heatwave", fr: "canicule" },
    ],
  },
  {
    name: "Le corps et la santé",
    icon: "🩹",
    level: "avance",
    words: [
      { en: "ankle", fr: "cheville" },
      { en: "wrist", fr: "poignet" },
      { en: "elbow", fr: "coude" },
      { en: "thumb", fr: "pouce" },
      { en: "chin", fr: "menton" },
      { en: "forehead", fr: "front" },
      { en: "eyebrow", fr: "sourcil" },
      { en: "cheek", fr: "joue" },
      { en: "shoulder", fr: "épaule" },
      { en: "sprain", fr: "entorse" },
      { en: "cough", fr: "toux" },
      { en: "sneeze", fr: "éternuement" },
      { en: "dizzy", fr: ["étourdi", "pris de vertige"] },
      { en: "sore throat", fr: "mal de gorge" },
      { en: "plaster", fr: "pansement" },
    ],
  },
  {
    name: "Verbes : gestes et réactions",
    icon: "🙊",
    level: "avance",
    words: [
      { en: "to whisper", fr: "chuchoter" },
      { en: "to shout", fr: "crier" },
      { en: "to sigh", fr: "soupirer" },
      { en: "to frown", fr: "froncer les sourcils" },
      { en: "to blush", fr: "rougir" },
      { en: "to stare", fr: "fixer du regard" },
      { en: "to yawn", fr: "bâiller" },
      { en: "to nod", fr: "hocher la tête" },
      { en: "to shrug", fr: "hausser les épaules" },
      { en: "to grin", fr: "sourire jusqu'aux oreilles" },
      { en: "to sob", fr: "sangloter" },
      { en: "to giggle", fr: "glousser" },
      { en: "to wave", fr: "faire signe de la main" },
      { en: "to point", fr: "montrer du doigt" },
    ],
  },
  {
    name: "Verbes utiles au collège",
    icon: "📝",
    level: "avance",
    words: [
      { en: "to describe", fr: "décrire" },
      { en: "to compare", fr: "comparer" },
      { en: "to explain", fr: "expliquer" },
      { en: "to guess", fr: "deviner" },
      { en: "to imagine", fr: "imaginer" },
      { en: "to wonder", fr: "se demander" },
      { en: "to notice", fr: "remarquer" },
      { en: "to realize", fr: "se rendre compte" },
      { en: "to suggest", fr: "suggérer" },
      { en: "to complain", fr: "se plaindre" },
      { en: "to admit", fr: "admettre" },
      { en: "to pretend", fr: "faire semblant" },
      { en: "to succeed", fr: "réussir" },
      { en: "to improve", fr: ["améliorer", "s'améliorer"] },
      { en: "to avoid", fr: "éviter" },
      { en: "to borrow", fr: "emprunter" },
      { en: "to lend", fr: "prêter" },
    ],
  },
  {
    name: "L'école et le collège",
    icon: "🎓",
    level: "avance",
    words: [
      { en: "timetable", fr: "emploi du temps" },
      { en: "homework", fr: "devoirs" },
      { en: "subject", fr: "matière" },
      { en: "headteacher", fr: ["principal", "directeur"] },
      { en: "break", fr: "récréation" },
      { en: "canteen", fr: "cantine" },
      { en: "uniform", fr: "uniforme" },
      { en: "detention", fr: "retenue" },
      { en: "term", fr: "trimestre" },
      { en: "report", fr: "bulletin" },
      { en: "mark", fr: ["note"] },
      { en: "exam", fr: "examen" },
      { en: "revision", fr: "révisions" },
      { en: "locker", fr: "casier" },
      { en: "boarding school", fr: "internat" },
    ],
  },
  {
    name: "Les matières scolaires",
    icon: "🗂️",
    level: "avance",
    words: [
      { en: "Maths", fr: "les maths" },
      { en: "History", fr: "l'histoire" },
      { en: "Geography", fr: "la géographie" },
      { en: "Science", fr: "les sciences" },
      { en: "Biology", fr: "la biologie" },
      { en: "Chemistry", fr: "la chimie" },
      { en: "Physics", fr: "la physique" },
      { en: "Art", fr: "les arts plastiques" },
      { en: "Music", fr: "la musique" },
      { en: ["PE", "Physical Education"], fr: "l'EPS" },
      { en: "Technology", fr: "la technologie" },
      { en: "Drama", fr: "le théâtre" },
      { en: "Computing", fr: "l'informatique" },
      { en: "Latin", fr: "le latin" },
      { en: "Spanish", fr: "l'espagnol" },
    ],
  },
  {
    name: "Adjectifs et contraires",
    icon: "⚖️",
    level: "avance",
    words: [
      { en: "enormous", fr: "énorme" },
      { en: "tiny", fr: "minuscule" },
      { en: "ancient", fr: "ancien" },
      { en: "modern", fr: "moderne" },
      { en: "expensive", fr: "cher" },
      { en: "cheap", fr: "bon marché" },
      { en: "dangerous", fr: "dangereux" },
      { en: "safe", fr: ["sûr", "sans danger"] },
      { en: "rare", fr: "rare" },
      { en: "common", fr: "courant" },
      { en: "narrow", fr: "étroit" },
      { en: "wide", fr: "large" },
      { en: "deep", fr: "profond" },
      { en: "shallow", fr: "peu profond" },
      { en: "rough", fr: "rugueux" },
      { en: "smooth", fr: "lisse" },
    ],
  },
  {
    name: "Adverbes et connecteurs",
    icon: "🔗",
    level: "avance",
    words: [
      { en: "however", fr: "cependant" },
      { en: "therefore", fr: "donc" },
      { en: "although", fr: "bien que" },
      { en: "meanwhile", fr: "pendant ce temps" },
      { en: "suddenly", fr: "soudain" },
      { en: "finally", fr: "enfin" },
      { en: "especially", fr: "surtout" },
      { en: "actually", fr: ["en fait", "en réalité"] },
      { en: "probably", fr: "probablement" },
      { en: "hardly", fr: "à peine" },
      { en: "instead", fr: "à la place" },
      { en: "besides", fr: "d'ailleurs" },
      { en: "nowadays", fr: "de nos jours" },
      { en: "eventually", fr: ["finalement", "au bout du compte"] },
      { en: "unfortunately", fr: "malheureusement" },
      { en: "luckily", fr: "heureusement" },
    ],
  },
  {
    name: "La géographie et le monde",
    icon: "🗺️",
    level: "avance",
    words: [
      { en: "continent", fr: "continent" },
      { en: "island", fr: "île" },
      { en: "desert", fr: "désert" },
      { en: "rainforest", fr: "forêt tropicale" },
      { en: "glacier", fr: "glacier" },
      { en: "volcano", fr: "volcan" },
      { en: "earthquake", fr: "tremblement de terre" },
      { en: "border", fr: "frontière" },
      { en: "capital", fr: "capitale" },
      { en: "population", fr: "population" },
      { en: "climate", fr: "climat" },
      { en: "coast", fr: "côte" },
      { en: "flag", fr: "drapeau" },
      { en: "mountain range", fr: "chaîne de montagnes" },
    ],
  },
  {
    name: "En cuisine",
    icon: "👩‍🍳",
    level: "avance",
    words: [
      { en: "recipe", fr: "recette" },
      { en: "ingredient", fr: "ingrédient" },
      { en: "to bake", fr: "faire cuire au four" },
      { en: "to boil", fr: "faire bouillir" },
      { en: "to fry", fr: "faire frire" },
      { en: "to roast", fr: "rôtir" },
      { en: "to chop", fr: "hacher" },
      { en: "to peel", fr: "éplucher" },
      { en: "to stir", fr: "remuer" },
      { en: "spicy", fr: "épicé" },
      { en: "sour", fr: "acide" },
      { en: "bitter", fr: "amer" },
      { en: "ripe", fr: "mûr" },
      { en: "raw", fr: "cru" },
      { en: "tasty", fr: "savoureux" },
    ],
  },
];
