/* =========================================================================
   LISTES DE VOCABULAIRE  —  c'est le seul fichier à modifier pour changer les mots.
   =========================================================================

   Comment ça marche :
   - Chaque liste a un "name" (le texte du bouton), un "icon" (un emoji) et
     un tableau "words".
   - Chaque mot a "en" (anglais) et "fr" (français).

   PLUSIEURS TRADUCTIONS POSSIBLES :
   - "en" comme "fr" peuvent être une chaîne :           { en: "dog", fr: "chien" }
     ...ou un tableau de traductions acceptées :         { en: "teacher",
                                                            fr: ["professeur", "maître", "maîtresse"] }
   - La 1re valeur du tableau est celle qui s'affiche (le mot montré, et le
     bouton "bonne réponse"). Les suivantes sont juste "aussi acceptées" :
     elles ne seront jamais proposées comme mauvaise réponse, et si l'enfant
     en choisit une, c'est compté juste.

   Après avoir modifié ce fichier : recharge la page (ou redéploie).

   Ces listes couvrent le vocabulaire d'anglais du primaire (cycles 2 et 3 :
   du CP au CM2). Au premier lancement, seule la 1re liste est cochée.

   Conseils :
   - "icon" est facultatif (📚 par défaut). Un seul emoji.
   - Au moins 6 mots par liste (idéalement 8+) pour que le niveau "Difficile"
     (6 propositions) ait assez de choix.
   - Évite, dans une même liste, deux mots dont la traduction PRINCIPALE est identique.
   - Les accents et les majuscules ne comptent pas pour la correction.
   - Attention aux virgules : une après chaque { en: ..., fr: ... }.
   ========================================================================= */

window.VOCAB_LISTS = [
  {
    name: "Se saluer et être poli",
    icon: "👋",
    words: [
      { en: "hello", fr: ["bonjour", "salut"] },
      { en: "goodbye", fr: "au revoir" },
      { en: "good night", fr: "bonne nuit" },
      { en: "please", fr: ["s'il te plaît", "s'il vous plaît"] },
      { en: ["thank you", "thanks"], fr: "merci" },
      { en: "you're welcome", fr: ["de rien", "je t'en prie"] },
      { en: "yes", fr: "oui" },
      { en: "no", fr: "non" },
      { en: "sorry", fr: ["désolé", "pardon"] },
      { en: "excuse me", fr: ["excusez-moi", "pardon"] },
      { en: "see you soon", fr: "à bientôt" },
      { en: "welcome", fr: "bienvenue" },
    ],
  },
  {
    name: "Les nombres (1 à 20)",
    icon: "🔢",
    words: [
      { en: "one", fr: "un" },
      { en: "two", fr: "deux" },
      { en: "three", fr: "trois" },
      { en: "four", fr: "quatre" },
      { en: "five", fr: "cinq" },
      { en: "six", fr: "six" },
      { en: "seven", fr: "sept" },
      { en: "eight", fr: "huit" },
      { en: "nine", fr: "neuf" },
      { en: "ten", fr: "dix" },
      { en: "eleven", fr: "onze" },
      { en: "twelve", fr: "douze" },
      { en: "thirteen", fr: "treize" },
      { en: "fourteen", fr: "quatorze" },
      { en: "fifteen", fr: "quinze" },
      { en: "sixteen", fr: "seize" },
      { en: "seventeen", fr: "dix-sept" },
      { en: "eighteen", fr: "dix-huit" },
      { en: "nineteen", fr: "dix-neuf" },
      { en: "twenty", fr: "vingt" },
    ],
  },
  {
    name: "Les couleurs",
    icon: "🎨",
    words: [
      { en: "red", fr: "rouge" },
      { en: "blue", fr: "bleu" },
      { en: "green", fr: "vert" },
      { en: "yellow", fr: "jaune" },
      { en: "orange", fr: "orange" },
      { en: "pink", fr: "rose" },
      { en: "purple", fr: ["violet", "mauve"] },
      { en: "brown", fr: ["marron", "brun"] },
      { en: "black", fr: "noir" },
      { en: "white", fr: "blanc" },
      { en: ["grey", "gray"], fr: "gris" },
      { en: "gold", fr: ["doré", "or"] },
    ],
  },
  {
    name: "Les jours de la semaine",
    icon: "📅",
    words: [
      { en: "Monday", fr: "lundi" },
      { en: "Tuesday", fr: "mardi" },
      { en: "Wednesday", fr: "mercredi" },
      { en: "Thursday", fr: "jeudi" },
      { en: "Friday", fr: "vendredi" },
      { en: "Saturday", fr: "samedi" },
      { en: "Sunday", fr: "dimanche" },
      { en: "today", fr: "aujourd'hui" },
      { en: "tomorrow", fr: "demain" },
      { en: "yesterday", fr: "hier" },
      { en: "week", fr: "semaine" },
    ],
  },
  {
    name: "Les mois de l'année",
    icon: "🗓️",
    words: [
      { en: "January", fr: "janvier" },
      { en: "February", fr: "février" },
      { en: "March", fr: "mars" },
      { en: "April", fr: "avril" },
      { en: "May", fr: "mai" },
      { en: "June", fr: "juin" },
      { en: "July", fr: "juillet" },
      { en: "August", fr: "août" },
      { en: "September", fr: "septembre" },
      { en: "October", fr: "octobre" },
      { en: "November", fr: "novembre" },
      { en: "December", fr: "décembre" },
    ],
  },
  {
    name: "La famille",
    icon: "👪",
    words: [
      { en: ["mother", "mum", "mummy"], fr: ["mère", "maman"] },
      { en: ["father", "dad", "daddy"], fr: ["père", "papa"] },
      { en: "sister", fr: "sœur" },
      { en: "brother", fr: "frère" },
      { en: ["grandmother", "granny", "grandma"], fr: ["grand-mère", "mamie"] },
      { en: ["grandfather", "grandpa", "grandad"], fr: ["grand-père", "papi"] },
      { en: "parents", fr: "parents" },
      { en: "baby", fr: "bébé" },
      { en: "aunt", fr: "tante" },
      { en: "uncle", fr: "oncle" },
      { en: "cousin", fr: "cousin" },
      { en: "son", fr: "fils" },
      { en: "daughter", fr: "fille" },
    ],
  },
  {
    name: "Le corps et le visage",
    icon: "🧑",
    words: [
      { en: "head", fr: "tête" },
      { en: "hair", fr: "cheveux" },
      { en: "face", fr: "visage" },
      { en: "eye", fr: "œil" },
      { en: "ear", fr: "oreille" },
      { en: "nose", fr: "nez" },
      { en: "mouth", fr: "bouche" },
      { en: "tooth", fr: "dent" },
      { en: ["stomach", "tummy"], fr: ["ventre", "estomac"] },
      { en: "arm", fr: "bras" },
      { en: "hand", fr: "main" },
      { en: "finger", fr: "doigt" },
      { en: "leg", fr: "jambe" },
      { en: "foot", fr: "pied" },
      { en: "knee", fr: "genou" },
    ],
  },
  {
    name: "Animaux familiers et de la ferme",
    icon: "🐮",
    words: [
      { en: "dog", fr: "chien" },
      { en: "cat", fr: "chat" },
      { en: "rabbit", fr: "lapin" },
      { en: "hamster", fr: "hamster" },
      { en: "goldfish", fr: "poisson rouge" },
      { en: "horse", fr: "cheval" },
      { en: "cow", fr: "vache" },
      { en: "pig", fr: "cochon" },
      { en: "sheep", fr: "mouton" },
      { en: "hen", fr: "poule" },
      { en: "duck", fr: "canard" },
      { en: "goat", fr: "chèvre" },
      { en: "donkey", fr: "âne" },
    ],
  },
  {
    name: "Les animaux sauvages",
    icon: "🦁",
    words: [
      { en: "lion", fr: "lion" },
      { en: "tiger", fr: "tigre" },
      { en: "elephant", fr: "éléphant" },
      { en: "monkey", fr: "singe" },
      { en: "bear", fr: "ours" },
      { en: "wolf", fr: "loup" },
      { en: "fox", fr: "renard" },
      { en: "snake", fr: "serpent" },
      { en: "crocodile", fr: "crocodile" },
      { en: "giraffe", fr: "girafe" },
      { en: "zebra", fr: "zèbre" },
      { en: "kangaroo", fr: "kangourou" },
      { en: "panda", fr: "panda" },
      { en: "whale", fr: "baleine" },
    ],
  },
  {
    name: "La nourriture",
    icon: "🍽️",
    words: [
      { en: "bread", fr: "pain" },
      { en: "butter", fr: "beurre" },
      { en: "cheese", fr: "fromage" },
      { en: "egg", fr: "œuf" },
      { en: "milk", fr: "lait" },
      { en: "water", fr: "eau" },
      { en: ["juice", "fruit juice"], fr: ["jus", "jus de fruits"] },
      { en: "meat", fr: "viande" },
      { en: "chicken", fr: "poulet" },
      { en: "fish", fr: "poisson" },
      { en: "rice", fr: "riz" },
      { en: "pasta", fr: "pâtes" },
      { en: "soup", fr: "soupe" },
      { en: ["cake", "sponge cake"], fr: "gâteau" },
    ],
  },
  {
    name: "Les fruits et les légumes",
    icon: "🍎",
    words: [
      { en: "apple", fr: "pomme" },
      { en: "banana", fr: "banane" },
      { en: "orange", fr: "orange" },
      { en: "strawberry", fr: "fraise" },
      { en: "cherry", fr: "cerise" },
      { en: "grape", fr: "raisin" },
      { en: "lemon", fr: "citron" },
      { en: "pear", fr: "poire" },
      { en: "pineapple", fr: "ananas" },
      { en: "tomato", fr: "tomate" },
      { en: "potato", fr: "pomme de terre" },
      { en: "carrot", fr: "carotte" },
      { en: "onion", fr: "oignon" },
      { en: ["salad", "lettuce"], fr: ["salade", "laitue"] },
    ],
  },
  {
    name: "Les vêtements",
    icon: "👕",
    words: [
      { en: "shirt", fr: "chemise" },
      { en: "T-shirt", fr: "tee-shirt" },
      { en: ["jumper", "sweater", "pullover"], fr: ["pull", "pull-over"] },
      { en: ["trousers", "pants"], fr: "pantalon" },
      { en: "dress", fr: "robe" },
      { en: "skirt", fr: "jupe" },
      { en: "coat", fr: "manteau" },
      { en: "jacket", fr: ["veste", "blouson"] },
      { en: ["shoes", "trainers"], fr: ["chaussures", "baskets"] },
      { en: "socks", fr: "chaussettes" },
      { en: "hat", fr: "chapeau" },
      { en: "gloves", fr: "gants" },
      { en: "scarf", fr: "écharpe" },
    ],
  },
  {
    name: "L'école et la classe",
    icon: "🎒",
    words: [
      { en: "school", fr: "école" },
      { en: "teacher", fr: ["professeur", "maître", "maîtresse", "instituteur"] },
      { en: ["pupil", "student"], fr: "élève" },
      { en: "book", fr: "livre" },
      { en: "pen", fr: "stylo" },
      { en: "pencil", fr: "crayon" },
      { en: ["eraser", "rubber"], fr: "gomme" },
      { en: "ruler", fr: "règle" },
      { en: "notebook", fr: "cahier" },
      { en: ["schoolbag", "school bag"], fr: ["cartable", "sac d'école"] },
      { en: "glue", fr: "colle" },
      { en: "scissors", fr: "ciseaux" },
      { en: "desk", fr: "bureau" },
      { en: ["board", "blackboard", "whiteboard"], fr: "tableau" },
    ],
  },
  {
    name: "La maison",
    icon: "🏠",
    words: [
      { en: ["house", "home"], fr: "maison" },
      { en: "bedroom", fr: "chambre" },
      { en: "kitchen", fr: "cuisine" },
      { en: "bathroom", fr: "salle de bains" },
      { en: ["living room", "lounge"], fr: ["salon", "salle de séjour", "séjour"] },
      { en: "garden", fr: "jardin" },
      { en: "door", fr: "porte" },
      { en: "window", fr: "fenêtre" },
      { en: "wall", fr: "mur" },
      { en: "roof", fr: "toit" },
      { en: "bed", fr: "lit" },
      { en: "table", fr: "table" },
      { en: "chair", fr: "chaise" },
      { en: ["sofa", "couch", "settee"], fr: ["canapé", "sofa"] },
    ],
  },
  {
    name: "Le temps qu'il fait et les saisons",
    icon: "⛅",
    words: [
      { en: "spring", fr: "printemps" },
      { en: "summer", fr: "été" },
      { en: ["autumn", "fall"], fr: "automne" },
      { en: "winter", fr: "hiver" },
      { en: "sun", fr: "soleil" },
      { en: "rain", fr: "pluie" },
      { en: "wind", fr: "vent" },
      { en: "snow", fr: "neige" },
      { en: "cloud", fr: "nuage" },
      { en: ["storm", "thunderstorm"], fr: ["orage", "tempête"] },
      { en: "rainbow", fr: "arc-en-ciel" },
      { en: "ice", fr: "glace" },
      { en: ["hot", "warm"], fr: "chaud" },
      { en: "cold", fr: "froid" },
    ],
  },
  {
    name: "Les émotions et les sensations",
    icon: "😀",
    words: [
      { en: "happy", fr: ["content", "heureux"] },
      { en: "sad", fr: "triste" },
      { en: "angry", fr: ["fâché", "en colère", "furieux"] },
      { en: ["scared", "afraid", "frightened"], fr: ["effrayé", "apeuré"] },
      { en: "tired", fr: "fatigué" },
      { en: "surprised", fr: "surpris" },
      { en: "excited", fr: "excité" },
      { en: "bored", fr: "ennuyé" },
      { en: ["ill", "sick"], fr: "malade" },
      { en: "hungry", fr: "affamé" },
      { en: "thirsty", fr: "assoiffé" },
      { en: "worried", fr: "inquiet" },
      { en: "calm", fr: "calme" },
    ],
  },
  {
    name: "Les verbes d'action",
    icon: "🏃",
    words: [
      { en: "to run", fr: "courir" },
      { en: "to jump", fr: ["sauter", "bondir"] },
      { en: "to walk", fr: "marcher" },
      { en: "to swim", fr: "nager" },
      { en: "to sing", fr: "chanter" },
      { en: "to dance", fr: "danser" },
      { en: "to read", fr: "lire" },
      { en: "to write", fr: "écrire" },
      { en: "to draw", fr: "dessiner" },
      { en: "to play", fr: "jouer" },
      { en: "to eat", fr: "manger" },
      { en: "to drink", fr: "boire" },
      { en: "to sleep", fr: "dormir" },
      { en: "to climb", fr: "grimper" },
    ],
  },
  {
    name: "Les verbes essentiels",
    icon: "🔑",
    words: [
      { en: "to be", fr: "être" },
      { en: "to have", fr: "avoir" },
      { en: "to go", fr: "aller" },
      { en: "to come", fr: "venir" },
      { en: "to see", fr: "voir" },
      { en: "to want", fr: ["vouloir", "désirer"] },
      { en: ["to like", "to enjoy"], fr: ["aimer", "aimer bien"] },
      { en: "to know", fr: ["savoir", "connaître"] },
      { en: "to give", fr: "donner" },
      { en: "to take", fr: "prendre" },
      { en: ["to say", "to tell"], fr: "dire" },
      { en: "to think", fr: ["penser", "réfléchir", "croire"] },
      { en: "to open", fr: "ouvrir" },
      { en: "to close", fr: ["fermer", "refermer"] },
    ],
  },
  {
    name: "Les métiers",
    icon: "👷",
    words: [
      { en: "teacher", fr: ["professeur", "maître", "maîtresse", "instituteur"] },
      { en: "doctor", fr: ["médecin", "docteur"] },
      { en: "nurse", fr: ["infirmier", "infirmière"] },
      { en: "farmer", fr: ["fermier", "agriculteur"] },
      { en: "baker", fr: "boulanger" },
      { en: ["firefighter", "fireman"], fr: "pompier" },
      { en: ["police officer", "policeman"], fr: ["policier", "gendarme"] },
      { en: ["cook", "chef"], fr: ["cuisinier", "cuisinière", "chef"] },
      { en: "dentist", fr: "dentiste" },
      { en: "vet", fr: "vétérinaire" },
      { en: "pilot", fr: "pilote" },
      { en: "singer", fr: ["chanteur", "chanteuse"] },
      { en: "painter", fr: "peintre" },
    ],
  },
  {
    name: "La ville et les lieux",
    icon: "🏙️",
    words: [
      { en: "school", fr: "école" },
      { en: ["shop", "store"], fr: ["magasin", "boutique"] },
      { en: "park", fr: "parc" },
      { en: "library", fr: "bibliothèque" },
      { en: "hospital", fr: "hôpital" },
      { en: "museum", fr: "musée" },
      { en: ["cinema", "movie theater"], fr: "cinéma" },
      { en: ["station", "train station"], fr: "gare" },
      { en: "market", fr: "marché" },
      { en: "bakery", fr: "boulangerie" },
      { en: "restaurant", fr: "restaurant" },
      { en: "swimming pool", fr: "piscine" },
      { en: "playground", fr: ["cour de récréation", "cour"] },
    ],
  },
  {
    name: "Les transports",
    icon: "🚗",
    words: [
      { en: ["car", "automobile"], fr: ["voiture", "auto"] },
      { en: "bus", fr: ["bus", "autobus"] },
      { en: "train", fr: "train" },
      { en: ["plane", "aeroplane", "airplane"], fr: "avion" },
      { en: ["bike", "bicycle"], fr: ["vélo", "bicyclette"] },
      { en: "boat", fr: "bateau" },
      { en: "ship", fr: "navire" },
      { en: ["lorry", "truck"], fr: "camion" },
      { en: "taxi", fr: "taxi" },
      { en: "helicopter", fr: "hélicoptère" },
      { en: "tram", fr: "tramway" },
      { en: ["underground", "tube", "subway"], fr: "métro" },
      { en: "scooter", fr: "trottinette" },
    ],
  },
  {
    name: "La nature",
    icon: "🌳",
    words: [
      { en: "tree", fr: "arbre" },
      { en: "flower", fr: "fleur" },
      { en: "grass", fr: ["herbe", "gazon"] },
      { en: "leaf", fr: "feuille" },
      { en: ["forest", "wood", "woods"], fr: ["forêt", "bois"] },
      { en: "mountain", fr: "montagne" },
      { en: "river", fr: "rivière" },
      { en: "lake", fr: "lac" },
      { en: ["sea", "ocean"], fr: ["mer", "océan"] },
      { en: "beach", fr: "plage" },
      { en: "field", fr: "champ" },
      { en: "hill", fr: "colline" },
      { en: "moon", fr: "lune" },
      { en: "star", fr: "étoile" },
    ],
  },
  {
    name: "Halloween",
    icon: "🎃",
    words: [
      { en: "witch", fr: "sorcière" },
      { en: "ghost", fr: "fantôme" },
      { en: "pumpkin", fr: "citrouille" },
      { en: "skeleton", fr: "squelette" },
      { en: "bat", fr: "chauve-souris" },
      { en: "spider", fr: "araignée" },
      { en: "monster", fr: "monstre" },
      { en: "vampire", fr: "vampire" },
      { en: "broom", fr: ["balai", "balai de sorcière"] },
      { en: ["sweets", "candy"], fr: "bonbons" },
      { en: ["costume", "fancy dress"], fr: ["déguisement", "costume"] },
      { en: ["scary", "spooky"], fr: "effrayant" },
    ],
  },
  {
    name: "Noël",
    icon: "🎄",
    words: [
      { en: "Christmas", fr: "Noël" },
      { en: ["Father Christmas", "Santa", "Santa Claus"], fr: "Père Noël" },
      { en: ["present", "gift"], fr: "cadeau" },
      { en: "Christmas tree", fr: ["sapin", "sapin de Noël"] },
      { en: "star", fr: "étoile" },
      { en: "snow", fr: "neige" },
      { en: "reindeer", fr: "renne" },
      { en: ["sleigh", "sledge"], fr: "traîneau" },
      { en: "bell", fr: "cloche" },
      { en: "candle", fr: "bougie" },
      { en: "snowman", fr: "bonhomme de neige" },
      { en: "holly", fr: "houx" },
      { en: "angel", fr: "ange" },
    ],
  },
  {
    name: "Les adjectifs pour décrire",
    icon: "🔍",
    words: [
      { en: ["big", "large"], fr: ["grand", "gros"] },
      { en: ["small", "little"], fr: "petit" },
      { en: "long", fr: "long" },
      { en: "short", fr: "court" },
      { en: "new", fr: ["neuf", "nouveau"] },
      { en: "old", fr: ["vieux", "ancien"] },
      { en: ["fast", "quick"], fr: "rapide" },
      { en: "slow", fr: "lent" },
      { en: "easy", fr: "facile" },
      { en: ["hard", "difficult"], fr: ["difficile", "dur"] },
      { en: "strong", fr: "fort" },
      { en: "clean", fr: "propre" },
      { en: "dirty", fr: "sale" },
      { en: ["beautiful", "pretty"], fr: ["beau", "joli"] },
    ],
  },
];
